services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: solarwatch_db
    environment:
      - POSTGRES_DB=solarwatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    image: 'solarwatch_backend:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solarwatch_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/solarwatch
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
      - API_KEY=29547edcb04caf5fc38722690cb7f86b
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true


  frontend:
    image: 'solarwatch-frontend:latest'
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: solarwatch_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"


